spring:
  profiles: dev
  application:
    name: Demo
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    registerWithEureka: true   
  region: default
  registration:
    enabled: true    
  preferSameZone: true
  shouldUseDns: false
  decoderName: JacksonJson
  serviceUrl:
      default: localhost:8761/eureka/

